# Generated by Django 4.1.1 on 2022-09-23 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_alter_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='wishlist',
            field=models.ManyToManyField(related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
