# Generated by Django 4.1.1 on 2022-09-27 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0003_car_wishlist"),
    ]

    operations = [
        migrations.AlterModelManagers(name="car", managers=[],),
        migrations.AddField(
            model_name="car",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Payment ID"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
