# Generated by Django 4.1.1 on 2022-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_managers_car_payment_id_alter_car_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='payment_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment ID'),
        ),
    ]
