# Generated by Django 4.0.2 on 2022-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('azn', 'AZN'), ('usd', 'USD'), ('eur', 'EUR')], default='azn', max_length=3),
        ),
    ]
