# Generated by Django 4.0.2 on 2022-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='barter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
