# Generated by Django 4.0.2 on 2022-02-25 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_car_barter_alter_car_credit_alter_car_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_body', to='api.carbody'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_model', to='api.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='api.color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engine', to='api.engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel', to='api.fuel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_lever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gear_lever', to='api.gearlever'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmission', to='api.transmission'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='api.brand'),
        ),
    ]
