# Generated by Django 4.0.1 on 2022-02-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_car_made_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carequipment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='api.car'),
        ),
    ]
