from django.contrib import admin
from .models import (Brand, CarModel, CarBody, Color, City, Equipment, GearLever, Engine, Transmission, Fuel, Car, CarEquipment)

admin.site.register(Brand)
admin.site.register(CarModel)
admin.site.register(CarBody)
admin.site.register(Color)
admin.site.register(City)
admin.site.register(Equipment)
admin.site.register(GearLever)
admin.site.register(Engine)
admin.site.register(Transmission)
admin.site.register(Fuel)
admin.site.register(Car)
admin.site.register(CarEquipment)